name: popduke(Yonny Hao)
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

sass:
  sass_dir: _sass
  style: compressed
