name: Popduke's personal blog
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-feed
